# Generated by Django 3.0.8 on 2020-07-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200719_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.CharField(default='News', max_length=150),
        ),
        migrations.AddField(
            model_name='article',
            name='site_url',
            field=models.URLField(default='google.com'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
