# Generated by Django 3.1.1 on 2020-09-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20200923_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.TextField(default='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='site',
            field=models.TextField(default='News', max_length=99),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(),
        ),
    ]
