# Generated by Django 3.1.1 on 2020-09-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20200923_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
