# Generated by Django 3.1.1 on 2020-09-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_auto_20200923_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'url')},
        ),
    ]
