# Generated by Django 3.1.1 on 2020-09-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_article_timeadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='timeadded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
