# Generated by Django 3.1.1 on 2020-09-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_auto_20200925_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='timeadded',
        ),
    ]
