# Generated by Django 3.1.1 on 2020-09-25 03:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_article_timea_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='timea_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 3, 59, 41, 484802, tzinfo=utc)),
        ),
    ]
