# Generated by Django 3.1.1 on 2020-09-25 04:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_auto_20200925_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='timea_added',
        ),
        migrations.AddField(
            model_name='article',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 4, 0, 34, 380069, tzinfo=utc)),
        ),
    ]
