# Generated by Django 3.1.1 on 2020-09-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_auto_20200925_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time_added',
        ),
    ]
