# Generated by Django 3.1.1 on 2020-09-25 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_remove_article_time_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 14, 0, 45, 777193, tzinfo=utc)),
        ),
    ]
