# Generated by Django 3.1.1 on 2020-09-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_article_time_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
