# Generated by Django 3.1.1 on 2020-09-25 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_auto_20200925_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 14, 6, 36, 435412, tzinfo=utc)),
        ),
    ]
