# Generated by Django 3.0.8 on 2020-07-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200719_2237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'author')},
        ),
    ]
