# Generated by Django 3.0.8 on 2020-08-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
