# Generated by Django 3.0.8 on 2020-08-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200810_0725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
