# Generated by Django 3.0.8 on 2020-08-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20200827_0224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
